// Code generated by 'yaegi extract github.com/exoport/apex_process_ape/apescript'. DO NOT EDIT.

package apescriptsym

import (
	"github.com/exoport/apex_process_ape/apescript"
	"reflect"
)

func init() {
	Symbols["github.com/exoport/apex_process_ape/apescript/apescript"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Activate":       reflect.ValueOf(apescript.Activate),
		"Args":           reflect.ValueOf(apescript.Args),
		"ErrNoRuntime":   reflect.ValueOf(&apescript.ErrNoRuntime).Elem(),
		"Log":            reflect.ValueOf(apescript.Log),
		"PublishEvent":   reflect.ValueOf(apescript.PublishEvent),
		"PutBlob":        reflect.ValueOf(apescript.PutBlob),
		"ReadManifest":   reflect.ValueOf(apescript.ReadManifest),
		"RunPipeline":    reflect.ValueOf(apescript.RunPipeline),
		"RunPrompt":      reflect.ValueOf(apescript.RunPrompt),
		"RunTask":        reflect.ValueOf(apescript.RunTask),
		"ScanTranscript": reflect.ValueOf(apescript.ScanTranscript),
		"Skills":         reflect.ValueOf(apescript.Skills),

		// type definitions
		"Config":       reflect.ValueOf((*apescript.Config)(nil)),
		"Digest":       reflect.ValueOf((*apescript.Digest)(nil)),
		"Manifest":     reflect.ValueOf((*apescript.Manifest)(nil)),
		"PipelineOpts": reflect.ValueOf((*apescript.PipelineOpts)(nil)),
		"PromptOpts":   reflect.ValueOf((*apescript.PromptOpts)(nil)),
		"RunResult":    reflect.ValueOf((*apescript.RunResult)(nil)),
		"ScanResult":   reflect.ValueOf((*apescript.ScanResult)(nil)),
		"SkillInfo":    reflect.ValueOf((*apescript.SkillInfo)(nil)),
		"TaskOpts":     reflect.ValueOf((*apescript.TaskOpts)(nil)),
		"Totals":       reflect.ValueOf((*apescript.Totals)(nil)),
	}
}
