package sandbox

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

/*
Environment for LOGIN shells (PLAN-23 D9).

Everything aped derives per workspace — the durable tool caches, the egress proxy — is
injected as the container process's environment. That reaches `ape sandbox exec` and
`attach`, which inherit it, and it does NOT reach an ssh or VS Code Remote session:
sshd deliberately builds a fresh environment for each session rather than passing its
own along.

The consequence was live before delivery existed and had nothing to do with it: someone
working in a workspace over ssh got no GOPATH/GOBIN/GOMODCACHE/GOCACHE/ASDF_DATA_DIR, so
`go` and `asdf` wrote to the ephemeral rootfs instead of the durable /cache mounts —
silently defeating the offline-after-warmup property, and looking like "the cache is not
working" rather than an environment problem.

So the resolved env is also written to a file in the composed home, which the image's
/etc/profile.d entry sources. Two properties matter:

  * It is DERIVED SERVER-SIDE, from the mounts aped actually applied — same as the
    process env. A caller cannot inject a GOPATH here any more than it can there.
  * It carries an ALLOWLIST, not everything. Credential material legitimately lives in
    the process env (mode B injects ANTHROPIC_API_KEY, and per-VM NATS creds ride along),
    and writing that to a file on the host would widen its exposure for no benefit: an
    interactive shell needs paths and proxies, not secrets.
*/

// GuestProfileEnvFile is where the login-shell environment is written, relative to the
// composed home (which is the guest $HOME). Dotfile because it is machinery, not content
// the user edits — aped rewrites it on every create.
const GuestProfileEnvFile = ".ape-env"

// profileEnvAllowed are the exact keys worth handing to an interactive login shell. It is
// an allowlist because the failure mode of a denylist here is leaking a credential into a
// file, and a new secret-bearing variable added elsewhere must not silently qualify.
//
// The tool-cache keys are the point of the exercise (PLAN-22 D4); the proxy keys matter
// because a workspace's only route out is the CONNECT proxy, so a shell without them has
// no network even though the workspace does.
var profileEnvAllowed = map[string]bool{
	// Durable tool caches — must match the toolCaches table's Env keys.
	"GOPATH":           true,
	"GOBIN":            true,
	"GOMODCACHE":       true,
	"GOCACHE":          true,
	"ASDF_DATA_DIR":    true,
	"CARGO_HOME":       true,
	"npm_config_cache": true,
	"PUB_CACHE":        true,
	// Egress.
	"HTTPS_PROXY": true,
	"https_proxy": true,
	"HTTP_PROXY":  true,
	"http_proxy":  true,
	"NO_PROXY":    true,
	"no_proxy":    true,
	// Where the read-only framework is mounted.
	"APEX_FRAMEWORK_REPO": true,
}

// ProfileEnvLines renders the shell-sourceable subset of a workspace's environment.
// Sorted so the file is stable across creates and a diff means something changed.
func ProfileEnvLines(env []string) []string {
	keep := map[string]string{}
	for _, kv := range env {
		k, v, ok := strings.Cut(kv, "=")
		if !ok || !profileEnvAllowed[k] {
			continue
		}
		keep[k] = v
	}
	keys := make([]string, 0, len(keep))
	for k := range keep {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	out := make([]string, 0, len(keys))
	for _, k := range keys {
		// Single-quoted with embedded quotes escaped: these are paths and URLs aped
		// derived, but a file that is `source`d must not be able to run anything.
		out = append(out, fmt.Sprintf("export %s='%s'", k, strings.ReplaceAll(keep[k], `'`, `'\''`)))
	}
	return out
}

// WriteGuestProfileEnv writes the login-shell environment into the composed home.
//
// Always rewritten, and truncated when nothing qualifies: a stale file from a previous
// create pointing at caches this workspace no longer mounts would be worse than none.
func WriteGuestProfileEnv(stagingDir string, env []string) error {
	if strings.TrimSpace(stagingDir) == "" {
		return nil
	}
	body := "# Generated by aped for login shells (ssh / VS Code Remote), which do not\n" +
		"# inherit the container environment. Rewritten on every create — do not edit.\n"
	if lines := ProfileEnvLines(env); len(lines) > 0 {
		body += strings.Join(lines, "\n") + "\n"
	}
	path := filepath.Join(stagingDir, GuestProfileEnvFile)
	if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
		return fmt.Errorf("sandbox: write %s: %w", path, err)
	}
	return nil
}
