package sprint

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/exoport/apex_process_ape/internal/apexcfg"
	"github.com/stretchr/testify/require"
)

// realTracker is a sprint-status.yaml in the shape the framework writes:
// a generated header of comments, top-level timestamps, then the row map
// with epic rows interleaved.
const realTracker = `# sprint-status.yaml — generated by apex-sprint-sync. Do not hand-edit.
#
# STATUS DEFINITIONS
#   backlog      not started
#   drafted      story file written, not yet developed
#   in-progress  under development
#   review       awaiting review
#   done         reviewed and accepted
#   blocked      cannot proceed
#   cancelled    out of scope
created_at: '20260101000000'
updated_at: '20260301120000'
development_status:
  epic-1: in-progress   # projected, never asserted
  1-1: done
  1-2: done
  epic-2: backlog
  2-1: backlog
  2-2: backlog
  epic-3: in-progress
  3-1: done
  3-2: cancelled
  epic-3-retrospective: done
`

func writeTracker(t *testing.T, body string) string {
	t.Helper()
	dir := t.TempDir()
	path := filepath.Join(dir, "sprint-status.yaml")
	require.NoError(t, os.WriteFile(path, []byte(body), 0o644))
	return path
}

// --- Load / classify ---

func TestLoad_ClassifiesRows(t *testing.T) {
	tracker, err := Load(writeTracker(t, realTracker))
	require.NoError(t, err)

	kinds := map[string]string{}
	for _, r := range tracker.Rows {
		kinds[r.Key] = r.Kind
	}
	require.Equal(t, KindEpic, kinds["epic-1"])
	require.Equal(t, KindStory, kinds["1-1"])
	require.Equal(t, KindRetrospective, kinds["epic-3-retrospective"],
		"a retrospective row is classified out, not treated as a story")

	require.Equal(t, "20260301120000", tracker.TopLevelString("updated_at"))
}

func TestClassify(t *testing.T) {
	cases := map[string]string{
		"epic-1":               KindEpic,
		"epic-12":              KindEpic,
		"1-1":                  KindStory,
		"12-3":                 KindStory,
		"12-3-slug":            KindStory,
		"12-3_slug":            KindStory,
		"epic-3-retrospective": KindRetrospective,
		"retrospective-2026":   KindRetrospective,
		"something-else":       KindOther,
	}
	for key, want := range cases {
		require.Equal(t, want, classify(key), "key %q", key)
	}
}

func TestLoad_MissingFileIsNotAnError(t *testing.T) {
	tracker, err := Load(filepath.Join(t.TempDir(), "nope.yaml"))
	require.NoError(t, err)
	require.True(t, tracker.Missing)
}

func TestNormalizeStatus(t *testing.T) {
	require.Equal(t, StatusReadyForDev, NormalizeStatus("drafted"))
	require.Equal(t, StatusReadyForDev, NormalizeStatus(" Drafted "))
	require.Equal(t, StatusReadyForDev, NormalizeStatus("ready-for-dev"))
	require.Equal(t, "done", NormalizeStatus("done"))
}

// --- Project: the truth table ---

func TestProject_TruthTable(t *testing.T) {
	rows := func(statuses ...string) []Row {
		out := make([]Row, 0, len(statuses))
		for i, s := range statuses {
			out = append(out, Row{
				Key: "7-" + string(rune('1'+i)), Status: s, Kind: KindStory, Epic: 7,
			})
		}
		return out
	}
	cases := []struct {
		name  string
		rows  []Row
		want  string
		unrec []string
	}{
		{"no rows at all", nil, "", nil},
		{"all cancelled", rows("cancelled", "cancelled"), "", nil},
		{"all done", rows("done", "done"), StatusDone, nil},
		{"all backlog", rows("backlog", "backlog"), StatusBacklog, nil},
		{"mixed", rows("done", "backlog"), StatusInProgress, nil},
		{"done plus cancelled closes", rows("done", "cancelled"), StatusDone, nil},
		{"backlog plus cancelled stays backlog", rows("backlog", "cancelled"), StatusBacklog, nil},
		{"blocked holds it open", rows("done", "blocked"), StatusInProgress, nil},
		{"blocked alone holds it open", rows("blocked"), StatusInProgress, nil},
		{"in-progress", rows("done", "in-progress"), StatusInProgress, nil},
		{"review holds it open", rows("done", "review"), StatusInProgress, nil},
		{"drafted holds it open", rows("done", "drafted"), StatusInProgress, nil},
		{"single done", rows("done"), StatusDone, nil},
		{
			"unrecognised can only hold open, never close",
			rows("done", "banana"), StatusInProgress,
			[]string{"banana"},
		},
		{
			"unrecognised alone still holds open",
			rows("banana"), StatusInProgress,
			[]string{"banana"},
		},
		{
			"unrecognised is named once",
			rows("banana", "banana"), StatusInProgress,
			[]string{"banana"},
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got, unrec := Project(tc.rows, 7)
			require.Equal(t, tc.want, got)
			require.Equal(t, tc.unrec, unrec)
		})
	}
}

func TestProject_IgnoresOtherEpicsAndKinds(t *testing.T) {
	rows := []Row{
		{Key: "7-1", Status: "done", Kind: KindStory, Epic: 7},
		{Key: "8-1", Status: "backlog", Kind: KindStory, Epic: 8},
		{Key: "epic-7", Status: "in-progress", Kind: KindEpic, Epic: 7},
		{Key: "epic-7-retrospective", Status: "backlog", Kind: KindRetrospective, Epic: 0},
	}
	got, _ := Project(rows, 7)
	require.Equal(t, StatusDone, got, "only epic 7's story rows count")
}

func TestEpicNumbersAndHasStoryRows(t *testing.T) {
	tracker, err := Load(writeTracker(t, realTracker))
	require.NoError(t, err)
	require.Equal(t, []int{1, 2, 3}, EpicNumbers(tracker.Rows))
	require.True(t, HasStoryRows(tracker.Rows, 1))
	require.False(t, HasStoryRows(tracker.Rows, 9))
}

// --- Reconcile ---

// TestReconcile_ChangesExactlyTwoLines is the targeted-write proof, and
// the test that fails against the obvious unmarshal/re-marshal
// implementation: every comment, the STATUS DEFINITIONS header, the row
// ordering and every untouched row must be byte-identical.
func TestReconcile_ChangesExactlyTwoLines(t *testing.T) {
	path := writeTracker(t, realTracker)
	before, err := os.ReadFile(path)
	require.NoError(t, err)

	// Epic 1's stories are all done, so its row moves in-progress -> done.
	res, err := Reconcile(path, ReconcileOptions{Epic: 1, Timestamp: "20260401090000"})
	require.NoError(t, err)
	require.True(t, res.Written)
	require.Len(t, res.Changes, 1)
	require.Equal(t, "in-progress", res.Changes[0].From)
	require.Equal(t, StatusDone, res.Changes[0].To)

	after, err := os.ReadFile(path)
	require.NoError(t, err)

	beforeLines := strings.Split(string(before), "\n")
	afterLines := strings.Split(string(after), "\n")
	require.Len(t, afterLines, len(beforeLines), "no lines added or removed")

	var changed []int
	for i := range beforeLines {
		if beforeLines[i] != afterLines[i] {
			changed = append(changed, i)
		}
	}
	require.Len(t, changed, 2, "exactly two lines change: the epic row and updated_at")

	text := string(after)
	require.Contains(t, text, "epic-1: done   # projected, never asserted",
		"the row's trailing comment survives")
	require.Contains(t, text, "# STATUS DEFINITIONS", "the generated header survives")
	require.Contains(t, text, "updated_at: '20260401090000'")
	require.Contains(t, text, "created_at: '20260101000000'", "created_at is untouched")
	// Row ordering is preserved, which a re-marshal would alphabetise.
	require.Less(t, strings.Index(text, "epic-2"), strings.Index(text, "2-1"))
}

func TestReconcile_NoOpWhenAlreadyCorrect(t *testing.T) {
	path := writeTracker(t, realTracker)
	before, err := os.ReadFile(path)
	require.NoError(t, err)

	// Epic 2 is all backlog and its row already says backlog.
	res, err := Reconcile(path, ReconcileOptions{Epic: 2, Timestamp: "20260401090000"})
	require.NoError(t, err)
	require.False(t, res.Changed())
	require.False(t, res.Written)

	after, err := os.ReadFile(path)
	require.NoError(t, err)
	require.Equal(t, before, after, "updated_at must NOT move when nothing changed")
}

func TestReconcile_All(t *testing.T) {
	path := writeTracker(t, realTracker)
	res, err := Reconcile(path, ReconcileOptions{All: true, Timestamp: "20260401090000"})
	require.NoError(t, err)

	moved := map[int]string{}
	for _, c := range res.Changes {
		moved[c.Epic] = c.To
	}
	require.Equal(t, StatusDone, moved[1], "all done")
	require.NotContains(t, moved, 2, "already backlog")
	require.Equal(t, StatusDone, moved[3], "3-1 done + 3-2 cancelled closes epic 3")
}

func TestReconcile_CheckWritesNothing(t *testing.T) {
	path := writeTracker(t, realTracker)
	before, err := os.ReadFile(path)
	require.NoError(t, err)

	res, err := Reconcile(path, ReconcileOptions{Epic: 1, Timestamp: "20260401090000", Check: true})
	require.NoError(t, err)
	require.True(t, res.Changed())
	require.False(t, res.Written)

	after, err := os.ReadFile(path)
	require.NoError(t, err)
	require.Equal(t, before, after)
}

// TestReconcile_UpdatedAtIsClampedNotMovedBackwards: a supplied timestamp
// earlier than the file's own is held, reported, and never fatal.
func TestReconcile_UpdatedAtIsClamped(t *testing.T) {
	path := writeTracker(t, realTracker)
	res, err := Reconcile(path, ReconcileOptions{Epic: 1, Timestamp: "20250101000000"})
	require.NoError(t, err)
	require.True(t, res.Clamped)
	require.Equal(t, "20260301120000", res.UpdatedAt, "held at the existing, later value")

	body, err := os.ReadFile(path)
	require.NoError(t, err)
	require.Contains(t, string(body), "updated_at: '20260301120000'")
}

func TestReconcile_EpicWithNoStoriesIsLeftAlone(t *testing.T) {
	path := writeTracker(t, `development_status:
  epic-9: in-progress
`)
	res, err := Reconcile(path, ReconcileOptions{Epic: 9, Timestamp: "20260401090000"})
	require.NoError(t, err)
	require.False(t, res.Changed())
	require.Len(t, res.Unchanged, 1)
	require.Contains(t, res.Unchanged[0].Reason, "no story rows")
}

func TestReconcile_AllCancelledIsLeftAlone(t *testing.T) {
	path := writeTracker(t, `development_status:
  epic-9: in-progress
  9-1: cancelled
  9-2: cancelled
`)
	res, err := Reconcile(path, ReconcileOptions{Epic: 9, Timestamp: "20260401090000"})
	require.NoError(t, err)
	require.False(t, res.Changed())
	require.Contains(t, res.Unchanged[0].Reason, "scope decision")
}

func TestReconcile_UnrecognisedStatusIsNamedNotFatal(t *testing.T) {
	path := writeTracker(t, `development_status:
  epic-9: backlog
  9-1: banana
`)
	res, err := Reconcile(path, ReconcileOptions{Epic: 9, Timestamp: "20260401090000"})
	require.NoError(t, err, "an unrecognised status is a content outcome, never an error")
	require.Equal(t, []string{"banana"}, res.Unrecognised)
	require.Len(t, res.Changes, 1)
	require.Equal(t, StatusInProgress, res.Changes[0].To, "it can only hold the epic open")
}

func TestReconcile_EpicNumberBoundaries(t *testing.T) {
	// epic-1 must not match rows of epic-12, and vice versa.
	path := writeTracker(t, `development_status:
  epic-1: backlog
  1-1: done
  epic-12: backlog
  12-1: backlog
`)
	res, err := Reconcile(path, ReconcileOptions{All: true, Timestamp: "20260401090000"})
	require.NoError(t, err)
	require.Len(t, res.Changes, 1)
	require.Equal(t, 1, res.Changes[0].Epic)

	body, err := os.ReadFile(path)
	require.NoError(t, err)
	require.Contains(t, string(body), "epic-1: done")
	require.Contains(t, string(body), "epic-12: backlog", "epic-12 is untouched")
}

// TestReconcile_BareStoryKeysCount documents a DELIBERATE divergence from
// reconcile-epic-status.py, so it is a decision on the record rather than an
// accident found later on someone's tracker.
//
// The Python's story-row pattern is `^(\d+)-\d+[-_]` — it requires a
// separator after the second number, so a bare `2-1` row is invisible to it
// and its epic is left unchanged. ape's pattern makes the suffix optional,
// so a bare row counts. ape's reading is the useful one (a bare key is still
// a story row, and an epic whose only rows are bare would otherwise never
// close), but it means a tracker carrying bare keys reconciles differently
// under the two implementations. Trackers written by the framework always
// carry the `_slug` suffix, so this only reaches hand-edited files.
func TestReconcile_BareStoryKeysCount(t *testing.T) {
	path := writeTracker(t, `development_status:
  epic-2: backlog
  2-1: done
  2-2: done
`)
	res, err := Reconcile(path, ReconcileOptions{Epic: 2, Timestamp: "20260401090000"})
	require.NoError(t, err)
	require.Len(t, res.Changes, 1,
		"a bare N-M row is a story row here; reconcile-epic-status.py ignores it")
	require.Equal(t, StatusDone, res.Changes[0].To)

	// And it says so, rather than silently being the more useful of the two.
	require.Equal(t, []string{"2-1", "2-2"}, res.BareRowKeys)
	require.NotEmpty(t, res.BareRowKeyRemediation)
}

// TestReconcile_BareRowKeysReportedEvenOnANoOp: the divergence is in what was
// COUNTED, not in what was written. A run that changes nothing can still have
// reached that answer differently from the script it replaces, so a no-op
// must report it too — otherwise the warning appears only on the runs that
// happened to mutate, which is the subset least in need of it.
func TestReconcile_BareRowKeysReportedEvenOnANoOp(t *testing.T) {
	path := writeTracker(t, `development_status:
  epic-2: done
  2-1: done
`)
	res, err := Reconcile(path, ReconcileOptions{Epic: 2, Timestamp: "20260401090000"})
	require.NoError(t, err)
	require.False(t, res.Changed(), "epic-2 is already done")
	require.Equal(t, []string{"2-1"}, res.BareRowKeys)
	require.Contains(t, res.BareRowKeyRemediation, "rename the row")
}

func TestReconcile_CanonicalKeysReportNothing(t *testing.T) {
	path := writeTracker(t, `development_status:
  epic-2: backlog
  2-1_refuse-a-long-name: done
`)
	res, err := Reconcile(path, ReconcileOptions{Epic: 2, Timestamp: "20260401090000"})
	require.NoError(t, err)
	require.Empty(t, res.BareRowKeys)
	require.Empty(t, res.BareRowKeyRemediation)
}

// TestReconcile_RoundTripVerificationRestoresOnCorruption is the guard the
// Python carries and a port loses easily: after the targeted write, re-read
// and prove nothing but the named rows moved. If the check fails the
// original bytes go back, because a tracker left corrupt on disk is read by
// every later writer.
func TestReconcile_RoundTripVerificationRestoresOnCorruption(t *testing.T) {
	original := `development_status:
  epic-1: backlog
  1-1_x: done
`
	path := writeTracker(t, original)

	// A row whose value is rewritten to something that re-reads as a
	// DIFFERENT value than the projection asked for is the shape of a
	// line-edit that went wrong. Simulate it by verifying directly against a
	// tracker snapshot that claims a change the file does not carry.
	before, err := Load(path)
	require.NoError(t, err)
	err = verifyWriteLanded(path, before, []ReconcileChange{{Key: "epic-1", To: "done"}})
	require.Error(t, err, "the file still says backlog, so the claimed change did not land")
	require.Contains(t, err.Error(), "round-trip verification failed")

	// A dropped row is caught too.
	require.NoError(t, os.WriteFile(path, []byte("development_status:\n  epic-1: done\n"), 0o644))
	err = verifyWriteLanded(path, before, []ReconcileChange{{Key: "epic-1", To: "done"}})
	require.ErrorContains(t, err, "row count changed 2 -> 1")

	// And a clean write passes.
	require.NoError(t, os.WriteFile(path,
		[]byte("development_status:\n  epic-1: done\n  1-1_x: done\n"), 0o644))
	require.NoError(t, verifyWriteLanded(path, before, []ReconcileChange{{Key: "epic-1", To: "done"}}))
}

func TestReconcile_RequiresScope(t *testing.T) {
	path := writeTracker(t, realTracker)
	_, err := Reconcile(path, ReconcileOptions{})
	require.Error(t, err)
	require.Contains(t, err.Error(), "--epic")
}

func TestReconcile_MissingTrackerIsAnError(t *testing.T) {
	_, err := Reconcile(filepath.Join(t.TempDir(), "nope.yaml"), ReconcileOptions{Epic: 1})
	require.Error(t, err)
}

// TestReconcile_ConcurrentEpicsBothLand is the lock test. Without the
// advisory lock this is a read-modify-write race and one of the two
// updates is silently lost — which is exactly what happens when
// per-epic sub-agents reconcile the same tracker in parallel.
func TestReconcile_ConcurrentEpicsBothLand(t *testing.T) {
	path := writeTracker(t, `development_status:
  epic-1: backlog
  1-1: done
  epic-2: backlog
  2-1: done
`)
	var wg sync.WaitGroup
	errs := make([]error, 2)
	for i, epic := range []int{1, 2} {
		wg.Add(1)
		go func(slot, e int) {
			defer wg.Done()
			_, err := Reconcile(path, ReconcileOptions{Epic: e, Timestamp: "20260401090000"})
			errs[slot] = err
		}(i, epic)
	}
	wg.Wait()
	require.NoError(t, errs[0])
	require.NoError(t, errs[1])

	body, err := os.ReadFile(path)
	require.NoError(t, err)
	require.Contains(t, string(body), "epic-1: done", "epic 1's update survived")
	require.Contains(t, string(body), "epic-2: done", "epic 2's update survived")
}

func TestLockFile_Serialises(t *testing.T) {
	path := filepath.Join(t.TempDir(), "sprint-status.yaml")
	require.NoError(t, os.WriteFile(path, []byte("development_status: {}\n"), 0o644))

	unlock, err := lockFile(path)
	require.NoError(t, err)

	// The goroutine must not call require (testifylint go-require): a
	// failed assertion there would abort the wrong goroutine. It reports
	// through the channel instead.
	acquired := make(chan error, 1)
	go func() {
		unlock2, lockErr := lockFile(path)
		if lockErr == nil {
			unlock2()
		}
		acquired <- lockErr
	}()

	select {
	case <-acquired:
		t.Fatal("the second lock acquired while the first was held")
	case <-time.After(150 * time.Millisecond):
	}
	unlock()
	require.NoError(t, <-acquired, "the second lock acquires once the first releases")
}

func TestSetRowLine_PreservesIndentAndComment(t *testing.T) {
	data := []byte("development_status:\n    epic-1: backlog    # keep me\n")
	out, ok := setRowLine(data, "epic-1", "done")
	require.True(t, ok)
	require.Equal(t, "development_status:\n    epic-1: done    # keep me\n", string(out))

	_, ok = setRowLine(data, "epic-9", "done")
	require.False(t, ok)
}

func TestSetRowLine_CRLF(t *testing.T) {
	data := []byte("development_status:\r\n  epic-1: backlog\r\n  1-1: done\r\n")
	out, ok := setRowLine(data, "epic-1", "done")
	require.True(t, ok)
	require.Equal(t, "development_status:\r\n  epic-1: done\r\n  1-1: done\r\n", string(out),
		"the CR must survive, or every line ending flips")
}

// --- VerifyRow ---

func TestVerifyRow_Codes(t *testing.T) {
	ctx := context.Background()

	t.Run("ok", func(t *testing.T) {
		path := writeTracker(t, realTracker)
		res := VerifyRow(ctx, path, "1-1", "done")
		require.Equal(t, VerifyOK, res.Code, res.Message)
	})

	t.Run("unreadable: missing file", func(t *testing.T) {
		res := VerifyRow(ctx, filepath.Join(t.TempDir(), "nope.yaml"), "1-1", "done")
		require.Equal(t, VerifyUnreadable, res.Code)
	})

	t.Run("unreadable: malformed yaml", func(t *testing.T) {
		path := writeTracker(t, "development_status: [oops\n")
		res := VerifyRow(ctx, path, "1-1", "done")
		require.Equal(t, VerifyUnreadable, res.Code)
	})

	t.Run("mismatch: key absent", func(t *testing.T) {
		path := writeTracker(t, realTracker)
		res := VerifyRow(ctx, path, "9-9", "done")
		require.Equal(t, VerifyMismatch, res.Code)
		require.Contains(t, res.Message, "absent")
	})

	t.Run("mismatch: value differs", func(t *testing.T) {
		path := writeTracker(t, realTracker)
		res := VerifyRow(ctx, path, "1-1", "in-progress")
		require.Equal(t, VerifyMismatch, res.Code)
		require.Equal(t, "done", res.Actual)
	})

	t.Run("timestamps unordered", func(t *testing.T) {
		path := writeTracker(t, `created_at: '20260301000000'
updated_at: '20260101000000'
development_status:
  1-1: done
`)
		res := VerifyRow(ctx, path, "1-1", "done")
		require.Equal(t, VerifyTimestampsUnordered, res.Code)
	})
}

// TestVerifyRow_BackwardsWriteAgainstGit is exit 5 — the code two review
// skills branch on. It needs a real commit to compare against.
func TestVerifyRow_BackwardsWriteAgainstGit(t *testing.T) {
	if _, err := exec.LookPath("git"); err != nil {
		t.Skip("git not available")
	}
	ctx := context.Background()
	dir := t.TempDir()
	git := func(args ...string) {
		cmd := exec.CommandContext(ctx, "git", args...)
		cmd.Dir = dir
		cmd.Env = append(os.Environ(),
			"GIT_AUTHOR_NAME=t", "GIT_AUTHOR_EMAIL=t@e", "GIT_COMMITTER_NAME=t", "GIT_COMMITTER_EMAIL=t@e")
		require.NoError(t, cmd.Run(), "git %v", args)
	}
	git("init", "-q")

	path := filepath.Join(dir, "sprint-status.yaml")
	committed := `created_at: '20260101000000'
updated_at: '20260301120000'
development_status:
  1-1: done
`
	require.NoError(t, os.WriteFile(path, []byte(committed), 0o644))
	git("add", ".")
	git("commit", "-qm", "tracker")

	// Now write an EARLIER updated_at: a backwards write.
	backwards := strings.Replace(committed, "20260301120000", "20260201120000", 1)
	require.NoError(t, os.WriteFile(path, []byte(backwards), 0o644))

	res := VerifyRow(ctx, path, "1-1", "done")
	require.Equal(t, VerifyBackwardsWrite, res.Code, res.Message)
	require.Equal(t, "20260301120000", res.Committed)
	require.Equal(t, "20260301120000", res.Clamp, "the repair value is reported, not guessed at")

	// And the forwards case passes.
	forwards := strings.Replace(committed, "20260301120000", "20260401120000", 1)
	require.NoError(t, os.WriteFile(path, []byte(forwards), 0o644))
	require.Equal(t, VerifyOK, VerifyRow(ctx, path, "1-1", "done").Code)
}

// TestVerifyRow_BackwardsWriteAgainstUnquotedCommittedValue is the case the
// Python this replaced waved through, and the reason VerifyRow compares the
// RENDERED value rather than a type-guarded one.
//
// A 14-digit timestamp written without quotes is valid YAML for an int, so
// `verify-sprint-status-row.py` — whose guard demanded a str — silently
// skipped the comparison and reported OK on a genuine backwards write. Two
// review skills branch on exit 5 by number, and its repair instruction is
// "re-write updated_at as the value this reports", so a missed 5 does not
// merely under-report: it lets a stale timestamp stand as committed truth.
//
// The asymmetry was found by the retired TestParity_SprintRowBackwardsWrite,
// which ran the real script side by side with this command. That gate could
// only ever fire against a pre-v0.11.0 framework, so the case lives here now
// — without it, nothing stops the render-then-compare being "simplified"
// back into the type guard that had the bug.
func TestVerifyRow_BackwardsWriteAgainstUnquotedCommittedValue(t *testing.T) {
	if _, err := exec.LookPath("git"); err != nil {
		t.Skip("git not available")
	}
	ctx := context.Background()
	dir := t.TempDir()
	git := func(args ...string) {
		cmd := exec.CommandContext(ctx, "git", args...)
		cmd.Dir = dir
		cmd.Env = append(os.Environ(),
			"GIT_AUTHOR_NAME=t", "GIT_AUTHOR_EMAIL=t@e", "GIT_COMMITTER_NAME=t", "GIT_COMMITTER_EMAIL=t@e")
		require.NoError(t, cmd.Run(), "git %v", args)
	}
	git("init", "-q")

	path := filepath.Join(dir, "sprint-status.yaml")
	// Unquoted: YAML decodes this as an int, not a string.
	committed := `updated_at: 20260301120000
development_status:
  1-1: done
`
	require.NoError(t, os.WriteFile(path, []byte(committed), 0o644))
	git("add", ".")
	git("commit", "-qm", "tracker")

	backwards := strings.Replace(committed, "20260301120000", "20260201120000", 1)
	require.NoError(t, os.WriteFile(path, []byte(backwards), 0o644))

	res := VerifyRow(ctx, path, "1-1", "done")
	require.Equal(t, VerifyBackwardsWrite, res.Code, res.Message)
	require.Equal(t, "20260301120000", res.Committed,
		"the committed value must render identically whether or not it was quoted")
}

// TestVerifyRow_CreatedEqualsUpdatedPassesTrivially documents why the
// committed comparison exists at all: comparing updated_at against
// created_at alone cannot catch a backwards write, because both are
// written in the same operation.
func TestVerifyRow_CreatedEqualsUpdatedPasses(t *testing.T) {
	path := writeTracker(t, `created_at: '20260101000000'
updated_at: '20260101000000'
development_status:
  1-1: done
`)
	res := VerifyRow(context.Background(), path, "1-1", "done")
	require.Equal(t, VerifyOK, res.Code)
}

func TestVerifyRow_NoGitIsNotAFailure(t *testing.T) {
	path := writeTracker(t, realTracker)
	res := VerifyRow(context.Background(), path, "1-1", "done")
	require.Equal(t, VerifyOK, res.Code, "outside a repo the committed comparison is simply skipped")
	require.Empty(t, res.Committed)
}

// --- RunCheck ---

func newCheckFixture(t *testing.T) (cfg *apexcfg.Resolved, write func(name, body string)) {
	t.Helper()
	root := t.TempDir()
	require.NoError(t, os.MkdirAll(filepath.Join(root, apexcfg.DirName), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(root, apexcfg.DirName, apexcfg.BaseFile),
		[]byte("project_name: fx\nextensions: []\ndevelopment_folder: development\n"+
			"implementation_folder: development/implementation\n"), 0o644))
	cfg, err := apexcfg.ResolveAt(root, nil)
	require.NoError(t, err)
	require.NoError(t, os.MkdirAll(cfg.Paths.Implementation, 0o755))
	write = func(name, body string) {
		require.NoError(t, os.WriteFile(filepath.Join(cfg.Paths.Implementation, name), []byte(body), 0o644))
	}
	return cfg, write
}

// storyFile writes a story the way the framework does: the file STEM is the
// story key the tracker rows on, and the frontmatter `story_id` is the
// separate dotted form. Every RunCheck fixture below uses it, so a
// regression to joining on story_id fails these tests rather than passing
// them — which is how the join bug survived the first time round.
func storyFile(t *testing.T, write func(name, body string), key, dottedID, status string) {
	t.Helper()
	write(key+".md", "---\nstory_id: \""+dottedID+"\"\nepic: \"1\"\nstatus: "+status+
		"\noutput_document: development/implementation/"+key+".md\n---\n\nx\n")
}

func TestRunCheck_Clean(t *testing.T) {
	cfg, write := newCheckFixture(t)
	write("sprint-status.yaml", "development_status:\n  1-1_greet-a-name: done\n")
	storyFile(t, write, "1-1_greet-a-name", "1.1", "done")

	report, err := RunCheck(cfg)
	require.NoError(t, err)
	require.True(t, report.OK(), "%+v", report.Findings)
	require.Equal(t, 1, report.Summary.StoryRows)
	require.Equal(t, 1, report.Summary.StoriesOnDisk)
}

func TestRunCheck_RowWithoutStory(t *testing.T) {
	cfg, write := newCheckFixture(t)
	write("sprint-status.yaml", "development_status:\n  1-1_greet-a-name: done\n  9-9_ghost: backlog\n")
	storyFile(t, write, "1-1_greet-a-name", "1.1", "done")

	report, err := RunCheck(cfg)
	require.NoError(t, err)
	require.Len(t, report.Findings, 1)
	require.Equal(t, CheckRowWithoutStory, report.Findings[0].Check)
	require.Equal(t, "9-9_ghost", report.Findings[0].Key)
}

func TestRunCheck_StoryWithoutRow(t *testing.T) {
	cfg, write := newCheckFixture(t)
	write("sprint-status.yaml", "development_status:\n  1-1_greet-a-name: done\n")
	storyFile(t, write, "1-1_greet-a-name", "1.1", "done")
	storyFile(t, write, "1-2_present-the-form", "1.2", "backlog")

	report, err := RunCheck(cfg)
	require.NoError(t, err)
	require.Len(t, report.Findings, 1)
	require.Equal(t, CheckStoryWithoutRow, report.Findings[0].Check)
	require.Equal(t, "1-2_present-the-form", report.Findings[0].Key)
	require.Equal(t, "1.2", report.Findings[0].StoryID,
		"the dotted id travels alongside the key, because they are different strings")
}

func TestRunCheck_StatusDivergenceNamesBothSides(t *testing.T) {
	cfg, write := newCheckFixture(t)
	write("sprint-status.yaml", "development_status:\n  1-1_greet-a-name: done\n")
	storyFile(t, write, "1-1_greet-a-name", "1.1", "in-progress")

	report, err := RunCheck(cfg)
	require.NoError(t, err)
	require.Len(t, report.Findings, 1)
	require.Equal(t, CheckStatusDivergence, report.Findings[0].Check)
	require.Equal(t, "done", report.Findings[0].Tracker)
	require.Equal(t, "in-progress", report.Findings[0].Story)
	require.Contains(t, report.Findings[0].Message, "neither is assumed correct")
}

// TestRunCheck_DraftedIsNotADivergence: normalising the tracker's
// `drafted` to a story file's `ready-for-dev` is what stops this reporting
// a divergence on every drafted story.
func TestRunCheck_DraftedIsNotADivergence(t *testing.T) {
	cfg, write := newCheckFixture(t)
	write("sprint-status.yaml", "development_status:\n  1-1_greet-a-name: drafted\n")
	storyFile(t, write, "1-1_greet-a-name", "1.1", "ready-for-dev")

	report, err := RunCheck(cfg)
	require.NoError(t, err)
	require.True(t, report.OK())
}

func TestRunCheck_EpicAndRetroRowsClassifiedOut(t *testing.T) {
	cfg, write := newCheckFixture(t)
	write("sprint-status.yaml", `development_status:
  epic-1: done
  epic-1-retrospective: done
  1-1_greet-a-name: done
`)
	storyFile(t, write, "1-1_greet-a-name", "1.1", "done")

	report, err := RunCheck(cfg)
	require.NoError(t, err)
	require.True(t, report.OK(), "epic and retro rows have no story file to diverge from")
	require.Equal(t, 1, report.Summary.EpicRows)
	require.Equal(t, 1, report.Summary.RetroRows)
}

// TestStoryKeyFromPath pins the join key itself.
func TestStoryKeyFromPath(t *testing.T) {
	require.Equal(t, "1-1_greet-a-name", StoryKeyFromPath("1-1_greet-a-name.md"))
	require.Equal(t, "1-1_greet-a-name", StoryKeyFromPath("development/implementation/1-1_greet-a-name.md"))
	require.Equal(t, "1-1", StoryKeyFromPath("1-1.md"))
	require.Equal(t, "no-extension", StoryKeyFromPath("no-extension"))
}

// TestRunCheck_BareRowKeyIsItsOwnFinding: `2-1` names no story file AND is
// counted differently by the two live reconcile implementations. One finding
// carries both halves plus the fix — reporting it as row_without_story would
// send a reader off to create `2-1.md` when the row is what is wrong.
func TestRunCheck_BareRowKeyIsItsOwnFinding(t *testing.T) {
	cfg, write := newCheckFixture(t)
	write("sprint-status.yaml", "development_status:\n  epic-2: backlog\n  2-1: done\n")

	report, err := RunCheck(cfg)
	require.NoError(t, err)
	require.Len(t, report.Findings, 1, "one finding, not two: %+v", report.Findings)

	f := report.Findings[0]
	require.Equal(t, CheckNonStandardRowKey, f.Check)
	require.Equal(t, "2-1", f.Key)
	require.Contains(t, f.Message, "reconcile-epic-status.py",
		"the message names the other implementation, because that is why it matters now")
	require.Contains(t, f.Message, "rename the row", "and it names the fix")
	require.Empty(t, findingsWithCheck(report.Findings, CheckRowWithoutStory),
		"the bare key IS why the file lookup failed; saying both would mislead")
}

// TestRunCheck_BareRowKeyNamesItsActualStory is the case the first cut of
// this check got wrong twice, and both times because the fixture's bare row
// was `2-1` — the same string the hardcoded example used, so a generic
// message read as a specific one, and no story file matched it, so the
// second finding never fired.
//
// With `7-3` and `7-3_payment-retry.md` on disk, both faults appear: the
// message must name THIS rename and not some other row's, and the story file
// must not also be reported as having no tracker row when it plainly has one.
func TestRunCheck_BareRowKeyNamesItsActualStory(t *testing.T) {
	cfg, write := newCheckFixture(t)
	write("sprint-status.yaml", "development_status:\n  epic-7: backlog\n  7-3: done\n")
	storyFile(t, write, "7-3_payment-retry", "7.3", "done")

	report, err := RunCheck(cfg)
	require.NoError(t, err)
	require.Len(t, report.Findings, 1,
		"one misnamed row is one problem, not two: %+v", report.Findings)

	f := report.Findings[0]
	require.Equal(t, CheckNonStandardRowKey, f.Check)
	require.Contains(t, f.Message, "rename the row `7-3` to `7-3_payment-retry`",
		"the fix names the pair this run already identified")
	require.NotContains(t, f.Message, "2-1", "no other project's row may appear in this message")
	require.NotContains(t, f.Message, "N-M",
		"the generic form is for callers that cannot know the answer; this one can")

	// The finding stands in for the two it suppressed, so it carries both sides.
	require.Equal(t, "7.3", f.StoryID)
	require.Equal(t, "7-3_payment-retry.md", f.Path)
	require.Equal(t, "done", f.Tracker)
	require.Equal(t, "done", f.Story)
	require.Equal(t, []string{"7-3_payment-retry"}, f.Candidates,
		"one candidate populates the same field two do, so a consumer reads one place")
	require.Empty(t, findingsWithCheck(report.Findings, CheckStoryWithoutRow),
		"the story HAS a row — it is just misnamed. Telling the reader to add one is "+
			"the same misdirection as telling them to create the missing file.")
}

// TestRunCheck_BareRowKeyWithNoCandidateReportsTheSearch: nothing on disk
// claims the row. The honest sentence states THAT — the fact this run
// established — rather than the generic advice, and above all it must not end
// by pointing at `ape sprint check`, which is the command printing it. A
// reader told to run the command they are already reading the output of gets
// the same answer twice.
func TestRunCheck_BareRowKeyWithNoCandidateReportsTheSearch(t *testing.T) {
	cfg, write := newCheckFixture(t)
	write("sprint-status.yaml", "development_status:\n  epic-7: backlog\n  7-3: done\n")
	storyFile(t, write, "8-1_unrelated", "8.1", "done")

	report, err := RunCheck(cfg)
	require.NoError(t, err)
	nonstandard := findingsWithCheck(report.Findings, CheckNonStandardRowKey)
	require.Len(t, nonstandard, 1)

	msg := nonstandard[0].Message
	require.Contains(t, msg, "no story file matches this row")
	require.Contains(t, msg, "the row is stale", "the second real option is named too")
	require.NotContains(t, msg, "ape sprint check",
		"this IS sprint check; it already looked and found nothing")
	require.Empty(t, nonstandard[0].Candidates)

	require.Len(t, findingsWithCheck(report.Findings, CheckStoryWithoutRow), 1,
		"8-1_unrelated genuinely has no row, and nothing suppressed that")
}

// TestRunCheck_BareRowKeyWithTwoCandidatesPicksNeither: two files could be
// this row. The rename target is a judgment, so the message names both and
// nothing is suppressed — each file really does lack a row of its own name.
func TestRunCheck_BareRowKeyWithTwoCandidatesPicksNeither(t *testing.T) {
	cfg, write := newCheckFixture(t)
	write("sprint-status.yaml", "development_status:\n  epic-7: backlog\n  7-3: done\n")
	storyFile(t, write, "7-3_payment-retry", "7.3", "done")
	storyFile(t, write, "7-3_payment-refund", "7.3", "done")

	report, err := RunCheck(cfg)
	require.NoError(t, err)
	nonstandard := findingsWithCheck(report.Findings, CheckNonStandardRowKey)
	require.Len(t, nonstandard, 1)
	require.Contains(t, nonstandard[0].Message, "7-3_payment-refund")
	require.Contains(t, nonstandard[0].Message, "7-3_payment-retry")
	require.Empty(t, nonstandard[0].Path, "no single owner was claimed")
	// Not deciding which file the row meant is a deliberate refusal. Making
	// the decider parse prose to learn what the options were is not.
	require.Equal(t, []string{"7-3_payment-refund", "7-3_payment-retry"},
		nonstandard[0].Candidates,
		"the options reach a consumer as data, not only as a sentence")
	require.Len(t, findingsWithCheck(report.Findings, CheckStoryWithoutRow), 2,
		"neither file was claimed, and both genuinely lack a row of their own name")
}

func TestMatchesBareRowKey(t *testing.T) {
	require.True(t, MatchesBareRowKey("7-3", "7-3_payment-retry"))
	require.True(t, MatchesBareRowKey("7-3", "7-3-payment-retry"))
	require.False(t, MatchesBareRowKey("1-1", "1-10_ten"),
		"a prefix test alone would claim epic 1 story 10 as a candidate for story 1")
	require.False(t, MatchesBareRowKey("7-3", "7-3"), "identical is not a rename")
	require.False(t, MatchesBareRowKey("7-3", "8-3_other"))
}

func TestRemediationFor(t *testing.T) {
	none := RemediationFor("7-3", nil)
	require.Contains(t, none, "no story file matches this row")
	require.Contains(t, none, "7-3", "it names the row it searched for")
	require.NotEqual(t, BareRowKeyRemediation, none,
		"RemediationFor is for a caller that HAS looked; the constant is for the one that has not")
	require.NotContains(t, none, "ape sprint check",
		"a caller that already searched must not defer to the command doing the searching")

	require.Contains(t, RemediationFor("7-3", []string{"7-3_payment-retry"}),
		"rename the row `7-3` to `7-3_payment-retry`")

	two := RemediationFor("7-3", []string{"7-3_a", "7-3_b"})
	require.Contains(t, two, "2 story files could be this row")
	require.Contains(t, two, "give the others a row of their own")
}

// TestBareRowKeyRemediation_IsForTheCallerThatCannotLook: the constant keeps
// its pointer at `ape sprint check` because `ape sprint reconcile` is
// tracker-only and genuinely cannot resolve the pair itself. That tail is
// honest there and nowhere else.
func TestBareRowKeyRemediation_IsForTheCallerThatCannotLook(t *testing.T) {
	require.Contains(t, BareRowKeyRemediation, "`N-M` -> `N-M_slug`",
		"generic, so it cannot be misread as naming a specific row")
	require.Contains(t, BareRowKeyRemediation, "ape sprint check")

	path := writeTracker(t, "development_status:\n  epic-7: backlog\n  7-3: done\n")
	res, err := Reconcile(path, ReconcileOptions{Epic: 7, Timestamp: "20260401090000"})
	require.NoError(t, err)
	require.Equal(t, BareRowKeyRemediation, res.BareRowKeyRemediation)
}

// TestRunCheck_CanonicalKeyWithNoFileIsStillRowWithoutStory keeps the two
// findings distinct: a well-formed key that names a missing file is a
// genuinely different problem from a malformed key.
func TestRunCheck_CanonicalKeyWithNoFileIsStillRowWithoutStory(t *testing.T) {
	cfg, write := newCheckFixture(t)
	write("sprint-status.yaml", "development_status:\n  2-1_refuse-a-long-name: done\n")

	report, err := RunCheck(cfg)
	require.NoError(t, err)
	require.Len(t, report.Findings, 1)
	require.Equal(t, CheckRowWithoutStory, report.Findings[0].Check)
}

func TestIsBareStoryRowKey(t *testing.T) {
	for _, key := range []string{"2-1", "12-34"} {
		require.True(t, IsBareStoryRowKey(key), "%q is bare", key)
	}
	for _, key := range []string{
		"2-1_slug", "2-1-slug", "epic-2", "epic-2-retrospective", "not-a-story", "2",
	} {
		require.False(t, IsBareStoryRowKey(key), "%q is not a bare STORY row key", key)
	}
}

func findingsWithCheck(findings []Finding, check string) []Finding {
	var out []Finding
	for i := range findings {
		if findings[i].Check == check {
			out = append(out, findings[i])
		}
	}
	return out
}

func TestRunCheck_MalformedTrackerIsOneFindingNotAnError(t *testing.T) {
	cfg, write := newCheckFixture(t)
	write("sprint-status.yaml", "development_status: [oops\n")

	report, err := RunCheck(cfg)
	require.NoError(t, err, "the command still exits 0")
	require.Len(t, report.Findings, 1)
	require.Equal(t, CheckTrackerUnreadable, report.Findings[0].Check)
}

func TestRunCheck_MissingTrackerIsClean(t *testing.T) {
	cfg, _ := newCheckFixture(t)
	report, err := RunCheck(cfg)
	require.NoError(t, err)
	require.True(t, report.OK())
}
