package framework_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/diegosz/apex_process_ape/internal/framework"
	"github.com/stretchr/testify/require"
)

func sampleMetadata() *framework.Metadata {
	return &framework.Metadata{
		ConfigSchemaVersion: "1",
		InstalledAt:         time.Date(2026, 5, 9, 18, 0, 0, 0, time.UTC),
		Framework: framework.RepoInfo{
			RepoOrigin: "https://github.com/diegosz/apex_process_framework.git",
			VersionTag: "v0.0.71",
			GitHash:    "1fb6791000000000000000000000000000000000",
			GitBranch:  "main",
		},
		Ape: framework.ApeInfo{Version: "0.0.6"},
		Sources: framework.Sources{
			Skills:    framework.SkillsSource{Count: 2, Paths: []string{".claude/skills/apex-foo", ".claude/skills/apex-bar"}},
			Pipelines: framework.PipelinesSource{Count: 1, Paths: []string{"_apex/pipelines/design.yaml"}},
			Config: framework.ConfigSource{
				Seeded:      true,
				ProjectName: "demo",
				Extensions:  []string{"ext-adrs"},
			},
			ConfigLocalExample: framework.ConfigLocalExampleSource{Seeded: true},
		},
	}
}

func TestWriteAndReadMetadata_Roundtrip(t *testing.T) {
	root := t.TempDir()
	want := sampleMetadata()

	require.NoError(t, framework.WriteMetadata(root, want))

	got, err := framework.ReadMetadata(root)
	require.NoError(t, err)
	require.Equal(t, want.InstalledAt.Format(time.RFC3339Nano), got.InstalledAt.Format(time.RFC3339Nano))
	require.Equal(t, want.Framework, got.Framework)
	require.Equal(t, want.Ape, got.Ape)
	require.Equal(t, want.Sources, got.Sources)
}

func TestWriteMetadata_HasGeneratedHeader(t *testing.T) {
	root := t.TempDir()
	require.NoError(t, framework.WriteMetadata(root, sampleMetadata()))

	data, err := os.ReadFile(filepath.Join(root, framework.ProjectMetadata))
	require.NoError(t, err)
	require.True(t, strings.HasPrefix(string(data), "# Generated by 'ape framework update'"),
		"file must begin with the generated-by header; got: %q", string(data[:80]))
}

func TestReadMetadata_ActionableErrorOnMissingFile(t *testing.T) {
	root := t.TempDir()
	_, err := framework.ReadMetadata(root)
	require.Error(t, err)
	require.Contains(t, err.Error(), "framework metadata not found")
	require.Contains(t, err.Error(), "ape framework update")
}

func TestReadMetadata_ErrorsOnMalformed(t *testing.T) {
	root := t.TempDir()
	require.NoError(t, os.MkdirAll(filepath.Join(root, "_apex"), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(root, framework.ProjectMetadata), []byte("\t::: not yaml :::"), 0o644))

	_, err := framework.ReadMetadata(root)
	require.Error(t, err)
	require.Contains(t, err.Error(), "parse")
}

func TestWriteMetadata_DefaultsConfigSchemaVersion(t *testing.T) {
	root := t.TempDir()
	m := sampleMetadata()
	m.ConfigSchemaVersion = ""

	require.NoError(t, framework.WriteMetadata(root, m))

	got, err := framework.ReadMetadata(root)
	require.NoError(t, err)
	require.Equal(t, framework.MetadataSchemaVersion, got.ConfigSchemaVersion)
}
