package framework

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"time"

	"gopkg.in/yaml.v3"
)

// MetadataSchemaVersion identifies the framework.yaml schema. Bump
// when the on-disk shape changes in a non-additive way; readers can
// then refuse to parse incompatible versions.
const MetadataSchemaVersion = "1"

// Metadata is the on-disk shape of <project>/_apex/framework.yaml.
// Written by `ape framework update`, read by `ape framework status`
// and downstream tools that need to know which framework version a
// project is pinned to.
//
//nolint:tagliatelle // framework.yaml uses snake_case for human readability; matches APEX project-bootstrap convention
type Metadata struct {
	ConfigSchemaVersion string    `json:"configSchemaVersion" yaml:"config_schema_version"`
	InstalledAt         time.Time `json:"installedAt"         yaml:"installed_at"`
	Framework           RepoInfo  `json:"framework"           yaml:"framework"`
	Ape                 ApeInfo   `json:"ape"                 yaml:"ape"`
	Sources             Sources   `json:"sources"             yaml:"sources"`
}

// RepoInfo records the framework repo state at install time.
//
//nolint:tagliatelle // framework.yaml uses snake_case for human readability
type RepoInfo struct {
	RepoOrigin string `json:"repoOrigin" yaml:"repo_origin"`
	VersionTag string `json:"versionTag" yaml:"version_tag"` // empty when HEAD has no exact tag
	GitHash    string `json:"gitHash"    yaml:"git_hash"`
	GitBranch  string `json:"gitBranch"  yaml:"git_branch"`
}

// ApeInfo records which ape binary performed the install.
type ApeInfo struct {
	Version string `json:"version" yaml:"version"`
}

// Sources records what was installed into the project tree.
//
//nolint:tagliatelle // framework.yaml uses snake_case for human readability
type Sources struct {
	Skills             SkillsSource             `json:"skills"             yaml:"skills"`
	Pipelines          PipelinesSource          `json:"pipelines"          yaml:"pipelines"`
	Config             ConfigSource             `json:"config"             yaml:"config"`
	ConfigLocalExample ConfigLocalExampleSource `json:"configLocalExample" yaml:"config_local_example"`
}

// SkillsSource records the skills installed on this run.
type SkillsSource struct {
	Count int      `json:"count" yaml:"count"`
	Paths []string `json:"paths" yaml:"paths"`
}

// PipelinesSource records the pipelines installed on this run.
type PipelinesSource struct {
	Count int      `json:"count" yaml:"count"`
	Paths []string `json:"paths" yaml:"paths"`
}

// ConfigSource records whether _apex/config.yaml was seeded and what
// the bootstrap chose for project_name + extensions. Cross-checked by
// `framework status` against the live config.yaml to surface drift.
//
//nolint:tagliatelle // framework.yaml uses snake_case for human readability
type ConfigSource struct {
	Seeded      bool     `json:"seeded"                yaml:"seeded"`
	ProjectName string   `json:"projectName,omitempty" yaml:"project_name,omitempty"`
	Extensions  []string `json:"extensions,omitempty"  yaml:"extensions,omitempty"`
}

// ConfigLocalExampleSource records whether the local-example file was
// seeded (it carries no values worth reflecting back).
type ConfigLocalExampleSource struct {
	Seeded bool `json:"seeded" yaml:"seeded"`
}

// metadataHeader is prepended to the YAML output. Plain text only —
// the user must be able to read it without tooling.
const metadataHeader = `# Generated by 'ape framework update'. Edits to this file will be
# overwritten on the next run. Track in git so all collaborators agree
# on which framework version is installed.
`

// MetadataPath returns the absolute path of framework.yaml inside a
// project root.
func MetadataPath(projectRoot string) string {
	return filepath.Join(projectRoot, ProjectMetadata)
}

// WriteMetadata serializes m to <projectRoot>/_apex/framework.yaml via
// an atomic write (tempfile + rename). The file gets a one-line
// generated-by header above the YAML.
func WriteMetadata(projectRoot string, m *Metadata) error {
	if m.ConfigSchemaVersion == "" {
		m.ConfigSchemaVersion = MetadataSchemaVersion
	}
	body, err := yaml.Marshal(m)
	if err != nil {
		return fmt.Errorf("marshal metadata: %w", err)
	}
	full := append([]byte(metadataHeader), body...)
	return AtomicWriteFile(MetadataPath(projectRoot), full, 0o644)
}

// NotInstalledError signals that <projectRoot>/_apex/framework.yaml is
// absent — the canonical "project never had `ape framework setup` run"
// state. It satisfies errors.Is(err, fs.ErrNotExist) so programmatic
// callers can still pattern-match on the underlying cause, but the
// rendered message hides Go's syscall-level "open …: no such file or
// directory" trailer in favor of the actionable hint.
type NotInstalledError struct {
	Path string
}

func (e *NotInstalledError) Error() string {
	return fmt.Sprintf(
		"framework metadata not found at %s — run \"ape framework setup\" to install",
		e.Path,
	)
}

func (e *NotInstalledError) Unwrap() error { return fs.ErrNotExist }

// ReadMetadata loads <projectRoot>/_apex/framework.yaml. Returns a
// *NotInstalledError when the file is absent.
func ReadMetadata(projectRoot string) (*Metadata, error) {
	path := MetadataPath(projectRoot)
	data, err := os.ReadFile(path)
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return nil, &NotInstalledError{Path: path}
		}
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	var m Metadata
	if err := yaml.Unmarshal(data, &m); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	return &m, nil
}
